
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


window = Tk()

window.geometry("948x700")
window.configure(bg = "#CEAB83")


canvas = Canvas(
    window,
    bg = "#CEAB83",
    height = 700,
    width = 948,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    23.0,
    27.0,
    anchor="nw",
    text="Меню",
    fill="#000000",
    font=("MontserratAlternates Bold", 36 * -1)
)

canvas.create_rectangle(
    42.0,
    95.0,
    907.0,
    666.0,
    fill="#D9D9D9",
    outline="")
window.resizable(False, False)
window.mainloop()
